# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
#
# Reference (https://github.com/kan-bayashi/ParallelWaveGAN/)


###########################################################
#                   DATA SETTING                          #
###########################################################
sampling_rate: 48000
save_path: "Validation/"
data:
    clean_path: "corpus"
    reverb_path: "output_speech"
    rir_path: "binaural"
    subset:
        train: "train"
        valid: "valid"
        test:  "test"
###########################################################
#                    STATISTIC SETTING                    #
###########################################################
analyzer: "exp/autoencoder/symAD_vctk_48000_hop300/checkpoint-200000steps.pkl"
stats_speech: "stats/symAD_vctk_48000_hop300_clean.npy"
stats_rir: "stats/symAD_vctk_48000_hop300_rir.npy"
